/**
 * Dashboard Export Utilities - Enhanced Version
 * Supports PDF, PNG, and shareable links
 */
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

// Color palette for PDF export
const PDF_COLORS = {
    primary: [99, 102, 241], // Indigo
    secondary: [79, 70, 229],
    background: [15, 23, 42], // Dark slate
    text: [248, 250, 252],
    muted: [148, 163, 184]
};

/**
 * Export dashboard to PNG with high quality
 */
export const exportToPNG = async (elementId: string, filename: string = 'dashboard.png') => {
    const element = document.getElementById(elementId);
    if (!element) {
        toast.error('Export element not found');
        return;
    }

    try {
        toast.loading('Generating PNG...');

        const canvas = await html2canvas(element, {
            scale: 2,
            backgroundColor: '#0f172a', // Dark background
            logging: false,
            useCORS: true,
            allowTaint: true
        });

        const link = document.createElement('a');
        link.download = filename;
        link.href = canvas.toDataURL('image/png', 1.0);
        link.click();

        toast.dismiss();
        toast.success('PNG exported successfully!');
    } catch (error) {
        toast.dismiss();
        toast.error('PNG export failed');
        console.error('PNG Export failed:', error);
        throw error;
    }
};

/**
 * Export dashboard to PDF with professional formatting
 */
export const exportToPDF = async (
    elementId: string,
    filename: string = 'dashboard.pdf',
    options?: {
        title?: string;
        includeHeader?: boolean;
        includeFooter?: boolean;
    }
) => {
    const element = document.getElementById(elementId);
    if (!element) {
        toast.error('Export element not found');
        return;
    }

    try {
        toast.loading('Generating PDF...');

        const canvas = await html2canvas(element, {
            scale: 2,
            backgroundColor: '#0f172a',
            logging: false,
            useCORS: true,
            allowTaint: true
        });

        const imgData = canvas.toDataURL('image/png', 1.0);
        const imgWidth = canvas.width;
        const imgHeight = canvas.height;

        // Create PDF with proper dimensions
        const pdfWidth = 297; // A4 landscape width in mm
        const pdfHeight = 210; // A4 landscape height in mm
        const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);

        const pdf = new jsPDF({
            orientation: 'landscape',
            unit: 'mm',
            format: 'a4'
        });

        // Add header if requested
        if (options?.includeHeader) {
            pdf.setFillColor(PDF_COLORS.primary[0], PDF_COLORS.primary[1], PDF_COLORS.primary[2]);
            pdf.rect(0, 0, pdfWidth, 15, 'F');

            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(14);
            pdf.setFont('helvetica', 'bold');
            pdf.text(options.title || 'AI Dashboard Report', 10, 10);

            pdf.setFontSize(10);
            pdf.setFont('helvetica', 'normal');
            pdf.text(new Date().toLocaleDateString(), pdfWidth - 30, 10);
        }

        // Calculate image position
        const xOffset = (pdfWidth - imgWidth * ratio * 0.264583) / 2;
        const yOffset = options?.includeHeader ? 20 : 5;

        // Add the dashboard image
        pdf.addImage(
            imgData,
            'PNG',
            xOffset,
            yOffset,
            imgWidth * ratio * 0.264583,
            imgHeight * ratio * 0.264583
        );

        // Add footer if requested
        if (options?.includeFooter) {
            pdf.setFillColor(PDF_COLORS.secondary[0], PDF_COLORS.secondary[1], PDF_COLORS.secondary[2]);
            pdf.rect(0, pdfHeight - 10, pdfWidth, 10, 'F');

            pdf.setTextColor(255, 255, 255);
            pdf.setFontSize(8);
            pdf.text('Generated by Smart AI Dashboard', 10, pdfHeight - 4);
            pdf.text(`Page 1 of 1`, pdfWidth - 25, pdfHeight - 4);
        }

        pdf.save(filename);

        toast.dismiss();
        toast.success('PDF exported successfully!');
    } catch (error) {
        toast.dismiss();
        toast.error('PDF export failed');
        console.error('PDF Export failed:', error);
        throw error;
    }
};

/**
 * Generate a shareable link for the dashboard
 */
export const generateShareLink = async (dashboardId: string): Promise<string> => {
    try {
        // Create a share token (in production, this would be a backend call)
        const shareToken = btoa(JSON.stringify({
            id: dashboardId,
            created: Date.now(),
            expires: Date.now() + (7 * 24 * 60 * 60 * 1000) // 7 days
        }));

        // Store the share data in localStorage
        const shareData = JSON.parse(localStorage.getItem('sharedDashboards') || '{}');
        shareData[shareToken] = {
            dashboardId,
            createdAt: new Date().toISOString()
        };
        localStorage.setItem('sharedDashboards', JSON.stringify(shareData));

        // Generate the share URL
        const shareUrl = `${window.location.origin}/shared/${shareToken}`;

        return shareUrl;
    } catch (error) {
        console.error('Failed to generate share link:', error);
        throw new Error('Failed to generate share link');
    }
};

/**
 * Copy share link to clipboard
 */
export const copyShareLink = async (dashboardId: string) => {
    try {
        const shareUrl = await generateShareLink(dashboardId);
        await navigator.clipboard.writeText(shareUrl);
        toast.success('Share link copied to clipboard!');
        return shareUrl;
    } catch (error) {
        toast.error('Failed to copy share link');
        throw error;
    }
};

/**
 * Save dashboard layout to localStorage
 */
export const saveDashboardLayout = (layout: any, dashboardId: string) => {
    try {
        const savedLayouts = JSON.parse(localStorage.getItem('dashboardLayouts') || '{}');
        savedLayouts[dashboardId] = {
            layout,
            savedAt: new Date().toISOString()
        };
        localStorage.setItem('dashboardLayouts', JSON.stringify(savedLayouts));
        toast.success('Layout saved!');
        return true;
    } catch (error) {
        toast.error('Failed to save layout');
        console.error('Failed to save layout:', error);
        return false;
    }
};

/**
 * Load dashboard layout from localStorage
 */
export const loadDashboardLayout = (dashboardId: string) => {
    try {
        const savedLayouts = JSON.parse(localStorage.getItem('dashboardLayouts') || '{}');
        return savedLayouts[dashboardId]?.layout || null;
    } catch (error) {
        console.error('Failed to load layout:', error);
        return null;
    }
};

/**
 * Export dashboard data to JSON
 */
export const exportToJSON = (data: any, filename: string = 'dashboard-data.json') => {
    try {
        const jsonString = JSON.stringify(data, null, 2);
        const blob = new Blob([jsonString], { type: 'application/json' });
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.download = filename;
        link.href = url;
        link.click();

        URL.revokeObjectURL(url);
        toast.success('JSON exported successfully!');
    } catch (error) {
        toast.error('JSON export failed');
        console.error('JSON export failed:', error);
    }
};

/**
 * Export dashboard data to CSV
 */
export const exportToCSV = (data: any[], filename: string = 'dashboard-data.csv') => {
    try {
        if (!data || data.length === 0) {
            toast.error('No data to export');
            return;
        }

        const headers = Object.keys(data[0]);
        const csvContent = [
            headers.join(','),
            ...data.map(row =>
                headers.map(header => {
                    const value = row[header];
                    // Escape quotes and wrap in quotes if contains comma
                    if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
                        return `"${value.replace(/"/g, '""')}"`;
                    }
                    return value;
                }).join(',')
            )
        ].join('\n');

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.download = filename;
        link.href = url;
        link.click();

        URL.revokeObjectURL(url);
        toast.success('CSV exported successfully!');
    } catch (error) {
        toast.error('CSV export failed');
        console.error('CSV export failed:', error);
    }
};
